backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "desc", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "baseImage", widget: "image" }